#!/bin/sh -e

user="Ominitay"
repo="ShellSaber"

printf "%s" "\
========================================
  #    Welcome to the ShellSaber     #
  #            installer!            #
========================================
  #   Getting ShellSaber version...  #
"

latest_version="$(curl -fsL -H 'Accept: application/vnd.github.v3+json' "https://api.github.com/repos/$user/$repo/releases" | jq -r ".[0] | .tag_name")"

[ "$latest_version" = "" ] && {
  printf "%s" "Error: There are no releases found.\n" > /dev/stderr
  exit 1
}

printf "%s" "\
  # Latest ShellSaber version: $latest_version #
========================================
  #     Downloading ShellSaber...    #
"

curl -fsL "https://github.com/$user/$repo/archive/$latest_version.tar.gz" > "/tmp/ShellSaber.tar.gz"

printf "%s" "\
  #      Downloaded ShellSaber.      #
========================================
  #       Extracting archive...      #
"

tar  -C "/tmp" -xzf "/tmp/ShellSaber.tar.gz"
rm -f "/tmp/ShellSaber.tar.gz"

printf "%s" "\
  #        Extracted archive.        #
========================================
  #        Installing files...       #
"

install -D -m 775 "/tmp/$repo-$latest_version/shaber" "$HOME/.local/bin/shaber"
install -D -m 664 "/tmp/$repo-$latest_version/config" "$HOME/.local/share/shaber/default/config"
rm -rf "/tmp/$repo-$latest_version"

printf "%s" "\
  #        Installed archive.        #
========================================
  #      Installation complete!      #
"
